name: Sphinx Docs

on: [push]

env:
  PYVER: "3.12"

jobs:
  sphinx:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Fonts
        run: |
          mkdir ~/.fonts
          wget -q https://github.com/adobe-fonts/source-serif/releases/download/4.005R/source-serif-4.005_Desktop.zip
          wget -q https://github.com/rsms/inter/releases/download/v4.0/Inter-4.0.zip
          unzip source-serif-4.005_Desktop.zip 'source-serif-4.005_Desktop/TTF/*' -d ~/.fonts/
          unzip Inter-4.0.zip 'extras/ttf/*' -d ~/.fonts/
          fc-cache -v
          sed -E -i 's/(sans-serif|system-ui)/Inter Display/g' assets/icons/*.svg

      - uses: actions/setup-python@v5
        with: { python-version: "${{ env.PYVER }}", cache: "pip" }

      - run: pip install -r requirements.txt

      - run: make fullsite

      - uses: actions/upload-artifact@v4
        with: { path: _build/html }
